import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  courseSidebar: [
    {
      type: 'category',
      label: 'Module 0: Course Overview',
      link: {
        type: 'doc',
        id: 'module-0-overview/chapter-0.1-overview', // Link to the first chapter of Module 0
      },
      items: [
        'module-0-overview/chapter-0.1-overview',
        'module-0-overview/chapter-0.2-weekly-structure',
        'module-0-overview/chapter-0.3-hardware-requirements',
        'module-0-overview/chapter-0.4-software-stack',
        'module-0-overview/chapter-0.5-capstone-design',
        'module-0-overview/chapter-0.6-assessment-rubrics',
        'module-0-overview/chapter-0.7-appendices',
      ],
    },
    {
      type: 'category',
      label: 'Module 1: The Robotic Nervous System (ROS 2)',
      link: {
        type: 'doc',
        id: 'module-1-ros2/chapter-1.1-intro-ros2',
      },
      items: [
        'module-1-ros2/chapter-1.1-intro-ros2',
        'module-1-ros2/chapter-1.2-nodes-topics',
        'module-1-ros2/chapter-1.3-rclpy-packages',
        'module-1-ros2/chapter-1.4-urdf-modeling',
        'module-1-ros2/chapter-1.5-launch-controllers',
        'module-1-ros2/chapter-1.6-rviz-gazebo',
        'module-1-ros2/chapter-1.7-assignment',
      ],
    },
    {
      type: 'category',
      label: 'Module 2: The Digital Twin (Gazebo & Unity)',
      link: {
        type: 'doc',
        id: 'module-2-digital-twin/chapter-2.1-understanding-dt',
      },
      items: [
        'module-2-digital-twin/chapter-2.1-understanding-dt',
        'module-2-digital-twin/chapter-2.2-gazebo-physics',
        'module-2-digital-twin/chapter-2.3-unity-hri',
        'module-2-digital-twin/chapter-2.4-urdf-sdf-models',
        'module-2-digital-twin/chapter-2.5-sensor-simulation',
        'module-2-digital-twin/chapter-2.6-interactive-scenes',
        'module-2-digital-twin/chapter-2.7-assignment',
      ],
    },
    {
      type: 'category',
      label: 'Module 3: The AI-Robot Brain (NVIDIA Isaac)',
      link: {
        type: 'doc',
        id: 'module-3-isaac/chapter-3.1-intro-isaac-sim',
      },
      items: [
        'module-3-isaac/chapter-3.1-intro-isaac-sim',
        'module-3-isaac/chapter-3.2-photorealistic-sim',
        'module-3-isaac/chapter-3.3-synthetic-data',
        'module-3-isaac/chapter-3.4-isaac-ros-perception',
        'module-3-isaac/chapter-3.5-isaac-ros-ros2',
        'module-3-isaac/chapter-3.6-humanoid-nav',
        'module-3-isaac/chapter-3.7-assignment',
      ],
    },
    {
      type: 'category',
      label: 'Module 4: Vision-Language-Action (VLA)',
      link: {
        type: 'doc',
        id: 'module-4-vla/chapter-4.1-intro-vla',
      },
      items: [
        'module-4-vla/chapter-4.1-intro-vla',
        'module-4-vla/chapter-4.2-whisper-voice',
        'module-4-vla/chapter-4.3-cognitive-planning',
        'module-4-vla/chapter-4.4-nl-ros2-actions',
        'module-4-vla/chapter-4.5-object-multimodal',
        'module-4-vla/chapter-4.6-voice-plan-nav',
        'module-4-vla/chapter-4.7-assignment',
      ],
    },
  ],
};

export default sidebars;
